[package]
name = "rtk-ins570"
version = "0.1.0"
authors = ["YdrMaster <ydrml@hotmail.com>"]
edition = "2021"
readme = "README.md"

[dependencies]
driver = { path = "../driver" }
serial-port = { path = "../serial-port" }
num-traits = "*"
chrono = "*"
